before_script:
  - CI_COMMIT_TAG=${CI_COMMIT_TAG}

  - if [[ $TESTTAG == ejan_* ]]; then
  -   echo '1111111111'
  -   ENV='ejan';
  - else
  -   echo '22222222222'
  -   if [[ $CI_COMMIT_TAG == ejan_* ]]; then
  -     echo '333333333333'
  -     ENV='ejan';
  -   else
  -     echo '4444444444444'
  -     ENV='general';
  -   fi
  - fi

  # get latest tag
  # - CI_COMMIT_TAG=${CI_COMMIT_TAG}
  # - echo $CI_COMMIT_TAG
  # - TEST='general'
  # - if [[ $CI_COMMIT_TAG == ejan_* ]]; then TEST='ejan'; else TEST='general'; fi
  # - echo $TEST

stages:
  - build
  - test

test-111:
  script:
    - echo 'bbbbbbbb'

aest:
  stage: test
  script:
    - echo 'test!!!'

build_tag1:
  script:
    - echo 'bbbbbbbb'

build_aaaa:
  stage: build
  script:
    - echo 'build!!!'

build_tag2:
  script:
    - echo 'cccccc'

